## Basic Configuration
baseurl = "/"
languageCode = "en"
relativeurls = true

title = "Walker Harrison"
theme = "hyde-hyde"

## Hugo Built-in Features
# disqusShortname = "your-disqus-shortname"
# googleAnalytics = "your-google-analytics-id"
# enableRobotsTXT = true

# summarylength = 30

#paginate = 5

## Site Settings
[params]
    author = "Author"
    title = "Title"
    # description = "..."
    authorimage = "/img/headshot.jpg"
    dateformat = "Jan 2, 2006"
    themeColor = "theme-base-0d"
    custom_css = ["css/mystyles.css"]
    ignorefiles = [ "data/.*", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

    # sidebar, copyright & license
    copyright = "htr3n"
    license = "CC BY-SA 4.0"
    licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
    showBuiltWith = false

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "github"
    
    # please choose either GraphComment or Disqus or Utterances
    #GraphCommentId = "..."
    #UtterancesRepo = "..." # https://utteranc.es/
    #UtterancesIssueTerm = "..." # pathname, url, title, og:title
    #UtterancesTheme = "..." # github-light or github-dark

    # Table of contents
    #toc = none, "hugo", or "tocbot"

## Social Accounts
[params.social]
    github = "<username>"
    instagram = "<username>"
    # xing = "<username>"
    linkedin = "<username>"
    twitter = "<username>"
    facebook = "<username>"
    # stackoverflow = "<username>"
    # telegram = "<username>"
    email = "your-email@example.com"
    # gravatar = "your-email@example.com"

## Main Menu
[[menu.main]]
    name = "blog"
    weight = 200
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "consulting"
    identifier = "consulting"
    weight = 300
    url = "/consulting/"
#[[menu.main]]
    #name = "about"
    #identifier = "about"
    #weight = 100
    #url = "/about/"
[[menu.main]]
    name = "resume"
    identifier = "resume"
    weight = 300
    url = "/resume/"